version: '3.1'
services:
  db:
    image: postgres:12.2-alpine
    environment: 
      POSTGRES_USER: web_server
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ruby_app_dev
    restart: unless-stopped
    ports:
      - 5432:5432 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rms_pos:
    build:
      context: './'
      dockerfile: 'Dockerfile'
    ports: 
      - 3000:3000
    volumes:
      - ..:/workspace:cached

    # # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    depends_on:
      - db

volumes:
  postgres-data:
